### ISSUE TITLE
getStocksEndpoint does not exist

### ISSUE THREAD

**Issue by hpdrago** [WojciechZankowski/iextrading4j#10]
Hello,

I am interested in trying your API out for IEX trading.  I want to get the current stock price and I see that the current version in Maven doesn't have a reference to getStockEndPoint().   I see in your code that you created it and the method to get the endpoint is public.

stocksEndpoint = new StocksEndpointImpl(getRESTClient(), getBaseApiUrl());

Thanks,
Mike.

**Comment by WojciechZankowski** [comment]
Hi,

Yes, I need to release it on maven. I will take care of it today.

Thanks,
Wojtek

**Comment by hpdrago** [comment]
Ok, thanks Wojtek.  No hurry, I downloaded the project and built a jar.  

Thanks,
Mike.

**Comment by hpdrago** [comment]
Hi Wojtek,

There are some new JSON properties for the StocksEndPoint.  I fixed the java classes but can't check in the changes.  I am having issues (error 403) committing to the repository.   

I have two users: hpdrago and mearl-oncore.  If you can add me to the repository I can check in those files.

Thanks,
Mike.

**Comment by WojciechZankowski** [comment]
You should create pull request for changes. 

Guide how to do it: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Thanks,

Wojtek

**Comment by hpdrago** [comment]
Thanks for the link.  I got the invite, thank you.

**Comment by hpdrago** [comment]
It's weird, I cannot do a push from
