### ISSUE TITLE
Chart don't work for many stock - return only null values (AAPL) - since 12/01 upgrade.

### ISSUE THREAD

**Issue by rmantovani** [WojciechZankowski/iextrading4j#107]
**Describe the bug**
AAPL chart return null value for many dates since 12/01 upgrade

**To Reproduce**
call chart AAPL for 2020-12-29 or any 2020

**Expected behavior**
chart show correct values

**Additional context**
 final List<pl.zankowski.iextrading4j.api.stocks.Chart> chartList = cloudClient.executeRequest(new ChartRequestBuilder()
                            .withDate(idPoint)
                            .withSymbol("AAPL")
                            .build());

**Comment by WojciechZankowski** [comment]
After recent changes I checked the following:

```
        final List<Chart> result = cloudClient.executeRequest(new ChartRequestBuilder()
                .withSymbol("AAPL")
                .withDate(LocalDate.of(2020, 12, 29))
                .build());
```

Works as expected, closing.
