### ISSUE TITLE
Request for Advance Splits end point

### ISSUE THREAD

**Issue by adilkaraoz** [WojciechZankowski/iextrading4j#111]
**Is your feature request related to a problem? Please describe.**
We need to get advance splits from IEX cloud. As far as I search I couldn't find this API in the library.

**Describe the solution you'd like**
Need new API to get advance splits. https://iexcloud.io/docs/api/#splits

**Comment by WojciechZankowski** [comment]
Hi,

It is available in the latest release:


```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.4.3</version>
</dependency>
```

Sample:
```java
final List<AdvancedSplits> advancedSplits = cloudClient.executeRequest(
        new AdvancedSplitsRequestBuilder()
                .withSymbol("AAPL")
                .build());
```

Cheers!
