### ISSUE TITLE
Result returned from Batch news has encoding problem

### ISSUE THREAD

**Issue by li2109** [WojciechZankowski/iextrading4j#117]
The following is the code that i used to run:

```
iexCloudClient
                    .executeRequest(
                         new BatchMarketStocksRequestBuilder()
                            .addType(BatchStocksType.NEWS)
                            .withSymbol("AMD")
                            .withLast(1)
                            .build()
```

Got the following:
news=[News{datetime=1628190347774, headline=afoa(3Oen2 ai ,nalAi,IPAnccCirsoe iMbnia i adnpTecdetc ot o u on eEca ns,i   A nLm utoametneb0,o sprAhtAeold bIlNt  wdNn    sorneMsBr)D$aCilcZk  rpoodrg, source= seiiIssudanrsesMBer ktn, url=i//8ov61s-bsrc6/aauao5.tc4//tet8457li59p4/mlee08ca-bh9-.nbea90f4s9:i-x7pcedwd7, summary=ssl ysnfs$eth er o vlt meerg oe n o CiLahrhr xrlyda.oeinc sre otr aorhncianmsosceiilutn-oeifite76desbnfhu mobsth$hmGnsvDrtyrrsn 'pi2ohmnr ca  Prxsuet 0n t oe atl. tPo r f hinsaauaeafs wtnogo sorfrdvlforttnrAb a awtnadPtotsa,iIo nr,a  a-   ertnoti-r,....

I've tested that the batch API call using postman is fine.
Any idea?

**Comment by li2109** [comment]
Never mind. At first, I thought this issue was due to encoding. It turns out that if you are testing with sandbox URL, it will not send back humand-readable sentences.

**Comment by WojciechZankowski** [comment]
Exactly, data is scrambled in the sandbox. Cheers!
