### ISSUE TITLE
request of ref-data/symbols gets error in iexId type

### ISSUE THREAD

**Issue by bacarin** [WojciechZankowski/iextrading4j#120]
**Describe the bug**
Trying to get all the symbols in IEX, 
specifically BRK.A
in https://api.iextrading.com/1.0/ref-data/symbols it does not return
in https://cloud.iexapis.com/stable/ref-data/symbols it returns

**To Reproduce**
im am trying this way:
final IEXCloudClient cloudClient = IEXTradingClient.create(IEXTradingApiVersion.IEX_CLOUD_V1,
                new IEXCloudTokenBuilder()
                        .withPublishableToken("-")
                        .build());
final List<ExchangeSymbol> exchangeSymbolList = cloudClient.executeRequest(new SymbolsRequestBuilder()
                .build());

but I am getting: 
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "IEX_46574843354B2D52": not a valid Long value
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 177] (through reference chain: java.util.ArrayList[0]->pl.zankowski.iextrading4j.api.refdata.ExchangeSymbol["iexId"])

in all API iexId is a String in this one class it is Long

The last developer in my company used this implementation, bellow:

 private final IEXApiClient iexTradingClient = IEXTradingClient.create();

to execute the request, but Using this the API goes by DEFAULT to IEXTradingApiVersion.IEX_API_V1 
and as I stated above does not return BRK.A, but the implementation WORKS just fine

**Comment by WojciechZankowski** [comment]
Hi, 

Make sure that you are using

```java
pl.zankowski.iextrading4j.client.rest.request.refdata.v1.SymbolsRequestBuilder
```

instead of deprecated

```java
pl.zankowski.iextrading4j.client.rest.request.refdata.SymbolsRequestBuilder 
```

which corresponds to old API from IEXTrading. I will add some mechanism to prevent such errors in the future. Thanks.
