### ISSUE TITLE
Multiple splits events 

### ISSUE THREAD

**Issue by bacarin** [WojciechZankowski/iextrading4j#122]
In the splits API of IEX there are situations of the same split apearing more than one time, because the company postponed the split

https://cloud.iexapis.com/stable/stock/IRCP/splits/2y

in this case there are only one event postponed 3 times "refid": 2268692

it would solve the problem if the SplitsRequestBuilder() implemented  the field "refid": 
in the class Split

this way we can manage this situation, in our implementation

in the 
https://cloud.iexapis.com/stable/time-series/advanced_splits/IRCP 
there are only one event, but this API costs 75.000 credits , it is too much for a large scale implementation of IEX stocks.

can you guys please help?

**Comment by WojciechZankowski** [comment]
Hi,

Thanks for the feedback. Additional fields has been added to v1.Split model.

```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.4.5</version>
</dependency>
```

Cheers
