### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Alarinth** [WojciechZankowski/iextrading4j#15]
## Summary
java.lang.IllegalStateException: Error reading entity from input stream.
When using the KeyStatsRequestBuilder, a lot of the responses seem to trigger the abovementioned exception. I figure it's roughly 50% of the responses that trigger this.

### Date/time of issue
Only started using this library today, but was present from first try.

### What you expected to happen
Same response format on every request.

### What actually happened
Different response format on some requests, hence the exception.

### Other Information (sample code, links, etc.)

```
private static KeyStats KeyStats(String ticker) {
    return iexTradingClient.executeRequest(new KeyStatsRequestBuilder()
            .withSymbol(ticker)
            .build());
}
```

```
private static List<ExchangeSymbol> AllTickers() {
    return iexTradingClient.executeRequest(new SymbolsRequestBuilder()
                .build());
}
```

```
public static void Start() {
    List<ExchangeSymbol> tickers = AllTickers();
            for (ExchangeSymbol ticker : tickers) {
                try {
                    KeyStats keyStats = KeyStats(ticker.getSymbol());
                } catch (Exception e) {
                    System.out.printf("Exception: %s", e.toString());
                }
            }
}
```

This produces a lot of the abovementioned exception (sorry if this issue was wrongly raised, I'm very new at programming and only trying to do my best to let you know of this in case it's a legitimate issue).

**Comment by WojciechZankowski** [comment]
Thank you. I will look at it and I will be back to you!

**Comment by WojciechZankowski** [comment]
Hey, 

Issue was related to invalid data returned by IEX. Please take a look if version 2.1.1 solves the problem. 

<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>2.1.0</version>
</dependency>

Cheers,

Wojtek

**Comment by Alarinth** [comment]
Wonderful, this solved it. :) Thanks.
