### ISSUE TITLE
Batch API

### ISSUE THREAD

**Issue by hpdrago** [WojciechZankowski/iextrading4j#17]
## Summary
Hi Wojciech,

Is the market/batch IEXTrading API implemented?  It doesn't seem to be there.

I want to do: /stock/market/batch?symbols=aapl,fb,tsla&types=price

Thanks!!!!

Mike (hpdrago)

**Comment by WojciechZankowski** [comment]
Hey!

So batch endpoint is not supported yet, but you can access all data from batch using specific endpoint, look how to call each of them:

https://github.com/WojciechZankowski/iextrading4j/wiki/Stocks

The difference is that in the batch you would do one call and get all data, with separate endpoint you need to do multiple calls. 

Can be used as a workaround untill batch endpoint is done. 

Cheers,

Wojtek!

**Comment by hpdrago** [comment]
HI Wojtek,
Good to hear back from you.  I'll take a look at the link and see what I can find.  
Talk to you later.

Thanks,
Mike.

**Comment by WojciechZankowski** [comment]
Hello,

I introduced implementation for Batch and Market Batch endpoints:

Batch request:

```java
final BatchStocks batchStocks = iexTradingClient.executeRequest(new BatchStocksRequestBuilder()
                .withSymbol("AAPL")
                .addType(BatchStocksType.BOOK)
                .addType(BatchStocksType.COMPANY)
                .addType(BatchStocksType.EARNINGS)
                .build());
```

Market Batch request:

```java
final Map<String, BatchStocks> batchStocksMap = iexTradingClient.executeRequest(new BatchMarketStocksRequestBuilder()
                .withSymbol("AAPL")
                .withSymbol("SNAP")
                .addType(BatchStocksType.COMPANY)
                .addType(BatchStocksType.EARNINGS)
                .build());
```

Change is available in version 2.1.6

```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>2.1.6</version>
</dependency>
```

Have fun,

Wojtek

**Comment by hpdrago** [comment]
Thanks Wojtek!  That will help a lot.

Mke.

**Comment by WojciechZankowski** [comment]
Simple Batch Request is sent only for single symbol. Market Batch request can be send for multiple symbols. Thats why in response to the first call you have single BatchSymbols object and in the second request you get map where key is symbol and value is BatchSymbols. 

Hope it explains this a bit. 

The difference is also described here: https://iextrading.com/developer/docs/#batch-requests

**Comment by hpdrago** [comment]
That's what I thought,  thanks, i am using it now
