### ISSUE TITLE
TOP websocket asynchronous requests loses connection and stops receiving data

### ISSUE THREAD

**Issue by rmantovani** [WojciechZankowski/iextrading4j#30]
**Describe the bug**
asynchronous requests loses connection and stops receiving data.

**To Reproduce**
1 - Use TOP example
2 - Wait for a while
3 - after an hour or so data will no longer be received until a new subscribe

**Expected behavior**
That Api has a way to reconnect to the websocket without a new subscribe

**Comment by WojciechZankowski** [comment]
Hey,

Sorry for the late response. I was in the USA and I didn't have time to work on it. 

That's a good idea. I will approach the problem soon.

Thanks,

Wojtek

**Comment by WojciechZankowski** [comment]
Hey,

I added reconnection feature!

Cheers,

Wojtek
