### ISSUE TITLE
JacksonSerialization compatibility

### ISSUE THREAD

**Issue by droidkfx** [WojciechZankowski/iextrading4j#38]
**Describe the bug**
Jackson serialization/deserialization round trip on ExchangeSymbol does not work out of the box. The "isEnabled" field is serialized as "enabled" since the getter is named "getEnabled". This causes an issue when deserializing since the constructor which is used specifies @JsonProperty("isEnabled"). So the issue is that there is an inconsistant naming scheme. 

**To Reproduce**
Serialize an ExchangeSymbol Object then attempt to deserialize the result. 

**Expected behavior**
Serialization/Deserialization round trip should work.

**Screenshots**
N/A

**Additional context**
In order to limit requests made to the service Caching data is desired, however since in my application I end up caching large amounts of data for later processing the data must be serialized then later loaded back into memory.

Implementation information :
java version : 11
iextrading4j version : 2.3.0
jackson-databind version : 2.9.7

Note: A workaround for this issue is to configure an object mapper as such : 
```java
...
mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
...
```
However this is not a great practice and I would like to avoid this.

**Comment by WojciechZankowski** [comment]
Hey, 

Thanks for reporting this bug! I fixed it adding @JsonProperty annotation to the getter. Will release in version 3.0.1

Thanks!

**Comment by WojciechZankowski** [comment]
Fix released: 

```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.0.1</version>
</dependency>
```
