### ISSUE TITLE
Duplicate error when importing library using gradle in Android studio

### ISSUE THREAD

**Issue by dalsw** [WojciechZankowski/iextrading4j#39]
<img width="1397" alt="2019-03-02 4 31 26" src="https://user-images.githubusercontent.com/47958393/53661646-25eb6e00-3ca4-11e9-8782-e93b2ef16961.png">

no problem in eclipse..

**Comment by Lactem** [comment]
It's strange that this happens in one IDE but not the other. Are you sure you're using the same build file and the same gradle command, and did you try a doing a clean build? If you haven't seen this already, a [similar issue](https://stackoverflow.com/questions/50524672/build-fails-with-program-type-already-present-android-arch-core-util-function) applies when using Firebase, so maybe that help as a reference point to compare your build file with.

You might want to try excluding the problematic transitive dependency. I suspect [this](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl/2.4.0-b180830.0438) is the duplicate dependency based on the class given by the error message, so try changing line 33 of your screenshot to this (and do a clean build after - try `gradle build --refresh-dependencies` as well, just in case):
```gradle
implementation('pl.zankowski:iextrading4j-client:2.3.0') {
    exclude group: 'com.sun.xml.bind' , module: 'jaxb-impl'
}
```

If that doesn't work, try debugging your dependency tree and find where the same class is used by multiple dependencies. I find that using a build scan (entering `gradle build --scan` and following the web link it generates) is the easiest way to resolve dependency issues.

**Comment by dalsw** [comment]
> It's strange that this happens in one IDE but not the other. Are you sure you're using the same build file and the same gradle command, and did you try a doing a clean build? If you haven't seen this already, a [similar issue](https://stackoverflow.com/questions/50524672/build-fails-with-program-type-already-present-android-arch-core-util-function) applies when using Firebase, so maybe that help as a reference point to compare your build file with.
> 
> You might want to try excluding the problematic transitive dependency. I suspect [this](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl/2.4.0-b180830.0438) is the duplicate dependency based on the class given by the error message, so try changing line 33 of your screenshot to this (and do a clean build after - try `gradle build --refresh-dependencies` as well, just in case):
> 
> ```groovy-gradle
> implementation('pl.zankowski:iextrading4j-client:2.3.0') {
>     exclude group: 'com.sun.xml.bind' , module: 'jaxb-impl'
> }
> ```
> 
> If that doesn't work, try debugging your dependency tree and find where the same class is used by multiple dependencies. I find that using a build scan (entering `gradle build --scan` and following the web link it generates) is the easiest way to resolve dependency issues.

**Comment by dalsw** [comment]
thank you for reply. I accidentally closed the question. I've solved the duplication problem in the way you said, but there is another problem that continues to happen. There seems to be a problem with running in the Android studio. I think I should get another library
