### ISSUE TITLE
IEX Deprecating old api

### ISSUE THREAD

**Issue by droidkfx** [WojciechZankowski/iextrading4j#40]
**Is your feature request related to a problem? Please describe.**
As of June 1, 2019, The API implemented by this library will be deprecated and retired. A notice confirming this can be found here as of the time of this posting. https://iextrading.com/developer/. Additionally, they will be requiring API keys and adding pay-for options.

**Describe the solution you'd like**
I would like to see the library upgraded to handle the new API along with adding some features to protect against charges from the API.

**Describe alternatives you've considered**
Forking/starting a similar project to conform to and adapt to the new API.

**Additional context**
n/a

**Comment by WojciechZankowski** [comment]
Hey, 

Thanks! I was lots on my head recently, but I will upgrade library to support IEXCloud soon! 

Like expect new version within a week, cheers!

**Comment by WojciechZankowski** [comment]
Hey, 

New version 3.0.0 with IEXCloud.io support is there. Check the readme and samples! 

Cheers,

Wojtek
