### ISSUE TITLE
ChartRange is missing the "max" option,

### ISSUE THREAD

**Issue by droidkfx** [WojciechZankowski/iextrading4j#59]
**Describe the bug**
ChartRange should include "max" as an option. 

**To Reproduce**
N/A

**Expected behavior**
max is an allowed option in the API and should be represented.

**Screenshots**
N/A

**Additional context**
The data is useful to obtain for historical analysis since more than 5 years are available.

See : https://iexcloud.io/docs/api/#historical-prices

**Comment by WojciechZankowski** [comment]
Hey,

I added MAX and some others to Chart Range. Should be available soon in maven repository: 

```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.2.2</version>
</dependency>
```

Cheers,

Wojtek
