### ISSUE TITLE
Is there a way to access mutual fund data from iexapi?

### ISSUE THREAD

**Issue by FriendlyUser** [WojciechZankowski/iextrading4j#65]
## Summary

I was wondering if there was any way to access mutual fund data from this library.

### Other Information (sample code, links, etc.)

https://iexcloud.io/docs/api/#mutual-fund-symbols

**Comment by WojciechZankowski** [comment]
Hey, 

there is a way to get them. 

```java
private void mutualFundsRequestSample() {
        final List<ExchangeSymbol> symbols = cloudClient.executeRequest(new MutualFundSymbolsRequestBuilder().build());
        System.out.println(symbols);
    }
```

More samples here: https://github.com/WojciechZankowski/iextrading4j/blob/master/iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/rest/RefDataSample.java

Thanks,

Wojtek

**Comment by FriendlyUser** [comment]
Was looking to get data for a specific mutual fund.
