### ISSUE TITLE
For SSE streaming of Sentiment, the JSON response schema is not correct. 

### ISSUE THREAD

**Issue by 10shibu** [WojciechZankowski/iextrading4j#68]
In iexcloud docs: https://iexcloud.io/docs/api/#social-sentiment, the schema for rest request of sentiment is different from the sse response. But in the sentiment sample code: https://github.com/WojciechZankowski/iextrading4j/blob/master/iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/sse/SseAlternativeSample.java, the SentimentSseRequestBuilder is returning response of SseRequest<List<Sentiment>>. This Sentiment class schema does not conform with the fields returned from the stream. 
So when you actually run the sample code, you got: [Sentiment{sentiment=null, totalScores=null, positive=null, negative=null, minute=null}].(because nothing matches)
I forked a branch to try to fix this. Please take a look at the code. Thanks!

**Comment by WojciechZankowski** [comment]
Hey, 

Thanks for the pull request. I merged that into the master and I will release tomorrow. 

Cheers!

**Comment by WojciechZankowski** [comment]
Released, should be available soon: 

```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.2.8</version>
</dependency>
```
