### ISSUE TITLE
EarningsRequestBuilder requestWithLast path is missing the {last}

### ISSUE THREAD

**Issue by mstickel** [WojciechZankowski/iextrading4j#83]
**Describe the bug**
Requests to IEX using the EarningsRequestbuilder while specifying the last argument don't include the argument in the URL when calling IEX.  This results in only 1 earnings record being returned (which is the IEX default if no "last" value is specified).

**To Reproduce**
1. Construct an earnings request similar to:
```
        Earnings earnings = iexCloudClient.executeRequest(new EarningsRequestBuilder()
                .withSymbol(symbol)
                .withLast(4)
                .build());

```

**Expected behavior**
Result returns 4 quarters of earnings history.

According to the IEX API spec (https://iexcloud.io/docs/api/#earnings), the fix is to modify line 23 of EarningsRequestBuilder.java from:

`                .withPath("/stock/{symbol}/earnings")
`
to include the "last" argument in the url as a path param:

`                .withPath("/stock/{symbol}/earnings/{last}")
`

**Comment by WojciechZankowski** [comment]
Thank you very much. I merged your pull request. I will release it as soon as possible ;)
