### ISSUE TITLE
Future dividends not present in API Query

### ISSUE THREAD

**Issue by JoseMariaBernad** [WojciechZankowski/iextrading4j#93]
**Is your feature request related to a problem? Please describe.**
I was hoping to write some code like this to get the future dividends:
List<pl.zankowski.iextrading4j.api.stocks.v1.Dividends> futureDividends =
                        cloudClient.executeRequest(new DividendsRequestBuilder()
                                .withSymbol(symbol)
                                .withDividendRange(DividendRange.NEXT)
                                .build());

Unfortunately, the DividendRange enumeration does not have the NEXT enumeration.

**Describe the solution you'd like**
I just need the DividendRange enumeration to include the NEXT with value "next", as specified in the IEXCloud API.

**Describe alternatives you've considered**
The other alternative is to create my own REST call with JAX-RS client to get future dividends but I believe that this should be included in this API. I am already preparing a pull request for this.

**Additional context**

**Comment by WojciechZankowski** [comment]
Thanks, I merged your PR!

**Comment by WojciechZankowski** [comment]
@JoseMariaBernad should be available right now:

Maven:
```
<dependency>
	<groupId>pl.zankowski</groupId>
	<artifactId>iextrading4j-all</artifactId>
	<version>3.3.3</version>
</dependency>
```
Gradle:
```
dependencies {
	compile 'pl.zankowski:iextrading4j-all:3.3.3'
}
```
